platform:ios,'9.0'
target'HoldGold'do

pod'SDWebImage'

pod 'AFNetworking', '~>3.2.1'

pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCCommonLog'
pod 'UMCAnalytics'
pod 'UMCPush'
pod 'UMCShare/UI'
pod 'UMCShare/Social/WeChat'
pod 'UMCShare/Social/QQ'
pod 'UMCShare/Social/Sina'

pod 'GTSDK', '2.3.1.0-noidfa'

pod 'JPush', '3.1.0'

pod 'WCDB',git: 'https://github.com/Tencent/wcdb.git' , branch: 'master'

pod 'MJExtension'

 pod 'QCloudCOSXML'

pod 'MBProgressHUD'

pod 'MJRefresh'

end

